[IMP] account_receipt_base: Report, Partner, Fiscal Position
SirTakobi/account-invoicing pull request #2
Opened 2023-03-30 08:53 UTC by SirTakobi

To be included in https://github.com/OCA/account-invoicing/pull/1427

2023-03-30 15:49 UTC, eLBati requested changes

2023-03-30 15:49 UTC, eLBati commented on account_receipt_base/views/res_partner_views.xml
> +                        <span class="o_stat_text">Invoiced Receipts</span>
I would use only "Receipts", as they are not invoices

2023-03-30 16:00 UTC, SirTakobi commented on account_receipt_base/views/res_partner_views.xml
> +                        <span class="o_stat_text">Invoiced Receipts</span>
Done

2023-03-31 04:44 UTC, eLBati approved these changes
LGTM

2023-03-31 07:21 UTC, merged